name: BetterStructures
version: '1.7.1'
main: com.magmaguy.betterstructures.BetterStructures
api-version: 1.14
depend: [ WorldEdit ]
softdepend:
  - EliteMobs
  - WorldGuard
  - WorldEdit
authors: [ MagmaGuy ]
description: A plugin that adds random structures to your Minecraft world!
website: magmaguy.com
commands:
  betterstructures:
    description: Main command
    aliases:
      - bs
