name: BetterStructures
version: '1.7.3'
main: com.magmaguy.betterstructures.BetterStructures
api-version: 1.14
depend: [ WorldEdit ]
softdepend:
  - EliteMobs
  - WorldGuard
  - WorldEdit
  - Terralith
  - Iris
  - Terra
  - TerraformGenerator
authors: [ MagmaGuy ]
description: A plugin that adds random structures to your Minecraft world!
website: magmaguy.com
commands:
  betterstructures:
    description: Main command
    aliases:
      - bs
permissions:
  betterstructures.setup:
    description: Gives admins access to the /betterstructures setup command
    default: op
  betterstructures.initialize:
    description: Gives admins access to the /betterstructures initialize command
    default: op
  betterstructures.generatemodules.slowly:
    description: Gives admins access to the /betterstructures generateModulesSlowly command
    default: op
  betterstructures.generatemodules.instantly:
    description: Gives admins access to the /betterstructures generateModulesInstantly command
    default: op