name: BetterStructures
version: '1.7.2'
main: com.magmaguy.betterstructures.BetterStructures
api-version: 1.14
depend: [ WorldEdit ]
softdepend:
  - EliteMobs
  - WorldGuard
  - WorldEdit
authors: [ MagmaGuy ]
description: A plugin that adds random structures to your Minecraft world!
website: magmaguy.com
commands:
  betterstructures:
    description: Main command
    aliases:
      - bs
permissions:
  betterstructures.setup:
    description: Gives admins access to the /betterstructures setup command
    default: op
  betterstructures.initialize:
    description: Gives admins access to the /betterstructures initialize command
    default: op
